import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { CheckCircle, XCircle, Clock, Search, FileCheck, AlertTriangle } from "lucide-react";

interface BidCheck { label: string; passed: boolean; }
interface BidProject { id: number; name: string; client: string; dueDate: string; readinessScore: number; checks: BidCheck[]; }

const MOCK_BIDS: BidProject[] = [
  { id: 1, name: "Riverside Medical Center Expansion", client: "HCA Healthcare", dueDate: "2026-05-10", readinessScore: 92, checks: [{ label: "Team Assigned", passed: true },{ label: "Documents Ready", passed: true },{ label: "Bonding Approved", passed: true },{ label: "Compliance Cleared", passed: true },{ label: "Estimate Complete", passed: true },{ label: "Review Scheduled", passed: false }] },
    { id: 2, name: "Downtown Office Tower Phase 2", client: "Pinnacle Development", dueDate: "2026-05-18", readinessScore: 67, checks: [{ label: "Team Assigned", passed: true },{ label: "Documents Ready", passed: true },{ label: "Bonding Approved", passed: false },{ label: "Compliance Cleared", passed: true },{ label: "Estimate Complete", passed: false },{ label: "Review Scheduled", passed: false }] },
      { id: 3, name: "Harbor Bridge Rehabilitation", client: "City of Portland", dueDate: "2026-06-01", readinessScore: 38, checks: [{ label: "Team Assigned", passed: true },{ label: "Documents Ready", passed: false },{ label: "Bonding Approved", passed: false },{ label: "Compliance Cleared", passed: false },{ label: "Estimate Complete", passed: false },{ label: "Review Scheduled", passed: false }] },
        { id: 4, name: "Westside Elementary School", client: "Portland USD", dueDate: "2026-05-25", readinessScore: 85, checks: [{ label: "Team Assigned", passed: true },{ label: "Documents Ready", passed: true },{ label: "Bonding Approved", passed: true },{ label: "Compliance Cleared", passed: true },{ label: "Estimate Complete", passed: true },{ label: "Review Scheduled", passed: false }] },
        ];

        function scoreColor(s: number) { if (s >= 80) return "bg-green-100 text-green-800 border-green-200"; if (s >= 50) return "bg-yellow-100 text-yellow-800 border-yellow-200"; return "bg-red-100 text-red-800 border-red-200"; }
        function scoreLabel(s: number) { if (s >= 80) return "Ready"; if (s >= 50) return "At Risk"; return "Not Ready"; }
        function progressColor(s: number) { if (s >= 80) return "bg-green-500"; if (s >= 50) return "bg-yellow-500"; return "bg-red-500"; }
        type FilterType = "all" | "ready" | "at-risk" | "not-ready";

        export default function BidReadinessDashboard() {
          const [filter, setFilter] = useState<FilterType>("all");
            const [search, setSearch] = useState("");
              const bids = MOCK_BIDS;
                const filtered = bids.filter((b) => {
                    const ms = b.name.toLowerCase().includes(search.toLowerCase()) || b.client.toLowerCase().includes(search.toLowerCase());
                        const mf = filter === "all" || (filter === "ready" && b.readinessScore >= 80) || (filter === "at-risk" && b.readinessScore >= 50 && b.readinessScore < 80) || (filter === "not-ready" && b.readinessScore < 50);
                            return ms && mf;
                              });
                                const totalReady = bids.filter((b) => b.readinessScore >= 80).length;
                                  const totalAtRisk = bids.filter((b) => b.readinessScore >= 50 && b.readinessScore < 80).length;
                                    const totalNotReady = bids.filter((b) => b.readinessScore < 50).length;
                                      return (
                                          <div className="p-6 space-y-6">
                                                <div className="flex items-center gap-3">
                                                        <FileCheck className="h-7 w-7 text-blue-600" />
                                                                <div>
                                                                          <h1 className="text-2xl font-bold text-gray-900">Bid Readiness Dashboard</h1>
                                                                                    <p className="text-sm text-gray-500">Go / No-Go tracker for active bid projects</p>
                                                                                            </div>
                                                                                                  </div>
                                                                                                        <div className="grid grid-cols-4 gap-4">
                                                                                                                <Card><CardContent className="pt-4"><div className="text-3xl font-bold text-gray-900">{bids.length}</div><div className="text-sm text-gray-500 mt-1">Total Bids</div></CardContent></Card>
                                                                                                                        <Card className="border-green-200"><CardContent className="pt-4"><div className="text-3xl font-bold text-green-600">{totalReady}</div><div className="text-sm text-gray-500 mt-1">Ready</div></CardContent></Card>
                                                                                                                                <Card className="border-yellow-200"><CardContent className="pt-4"><div className="text-3xl font-bold text-yellow-600">{totalAtRisk}</div><div className="text-sm text-gray-500 mt-1">At Risk</div></CardContent></Card>
                                                                                                                                        <Card className="border-red-200"><CardContent className="pt-4"><div className="text-3xl font-bold text-red-600">{totalNotReady}</div><div className="text-sm text-gray-500 mt-1">Not Ready</div></CardContent></Card>
                                                                                                                                              </div>
                                                                                                                                                    <div className="flex gap-3">
                                                                                                                                                            <div className="relative flex-1">
                                                                                                                                                                      <Search className="absolute left-3 top-2.5 h-4 w-4 text-gray-400" />
                                                                                                                                                                                <Input placeholder="Search bids or clients..." value={search} onChange={(e) => setSearch(e.target.value)} className="pl-9" />
                                                                                                                                                                                        </div>
                                                                                                                                                                                                <div className="flex gap-2">
                                                                                                                                                                                                          {(["all","ready","at-risk","not-ready"] as FilterType[]).map((f) => (
                                                                                                                                                                                                                      <Button key={f} variant={filter === f ? "default" : "outline"} size="sm" onClick={() => setFilter(f)}>
                                                                                                                                                                                                                                    {f === "all" ? "All" : f === "ready" ? "Ready" : f === "at-risk" ? "At Risk" : "Not Ready"}
                                                                                                                                                                                                                                                </Button>
                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                              <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                                                                                                                                                                                                                                                                                      {filtered.map((bid) => (
                                                                                                                                                                                                                                                                                                <Card key={bid.id} className="hover:shadow-md transition-shadow">
                                                                                                                                                                                                                                                                                                            <CardHeader className="pb-2">
                                                                                                                                                                                                                                                                                                                          <div className="flex items-start justify-between">
                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                            <CardTitle className="text-base font-semibold">{bid.name}</CardTitle>
                                                                                                                                                                                                                                                                                                                                                                              <p className="text-sm text-gray-500 mt-0.5">{bid.client}</p>
                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                              <Badge className={`text-xs font-semibold border ${scoreColor(bid.readinessScore)}`}>{scoreLabel(bid.readinessScore)}</Badge>
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <CardContent className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-2xl font-bold text-gray-900">{bid.readinessScore}%</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex-1"><div className="h-2 bg-gray-100 rounded-full overflow-hidden"><div className={`h-full rounded-full transition-all ${progressColor(bid.readinessScore)}`} style={{ width: `${bid.readinessScore}%` }} /></div></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex items-center gap-2 text-xs text-gray-500"><Clock className="h-3 w-3" /><span>Due: {new Date(bid.dueDate).toLocaleDateString()}</span></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="grid grid-cols-2 gap-1.5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {bid.checks.map((c) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div key={c.label} className="flex items-center gap-1.5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {c.passed ? <CheckCircle className="h-4 w-4 text-green-500 flex-shrink-0" /> : <XCircle className="h-4 w-4 text-red-400 flex-shrink-0" />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className={`text-xs ${c.passed ? "text-gray-700" : "text-gray-400"}`}>{c.label}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {bid.readinessScore < 80 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex items-center gap-2 p-2 bg-amber-50 rounded-md border border-amber-100">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <AlertTriangle className="h-4 w-4 text-amber-500 flex-shrink-0" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="text-xs text-amber-700">{bid.checks.filter((c) => !c.passed).length} item(s) need attention before bid submission.</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {filtered.length === 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="col-span-2 text-center py-12 text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <FileCheck className="h-10 w-10 mx-auto mb-3 opacity-30" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>No bids match your filter.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }