export interface FieldDef {
  label: string;
  key: string;
  format?: "currency" | "date" | "percentage";
}

export interface EntityConfig {
  displayName: string;
  apiPath: string;
  listPath: string;
  nameField: string;
  statusField: string;
  fields: FieldDef[];
}

export const entityDetailConfig: Record<string, EntityConfig> = {
  project: {
    displayName: "Project",
    apiPath: "/api/projects",
    listPath: "/projects/active",
    nameField: "name",
    statusField: "status",
    fields: [
      { label: "Project Number", key: "projectNumber" },
      { label: "Name", key: "name" },
      { label: "Status", key: "status" },
      { label: "Client", key: "clientName" },
      { label: "Project Manager", key: "projectManagerName" },
      { label: "Contract Type", key: "contractType" },
      { label: "Contract Value", key: "contractValue", format: "currency" },
      { label: "Start Date", key: "startDate", format: "date" },
      { label: "Expected End Date", key: "expectedEndDate", format: "date" },
      { label: "Location", key: "location" },
      { label: "Completion", key: "completionPercentage", format: "percentage" },
      { label: "Description", key: "description" },
    ],
  },
  task: {
    displayName: "Task",
    apiPath: "/api/tasks",
    listPath: "/execution/tasks",
    nameField: "name",
    statusField: "status",
    fields: [
      { label: "Name", key: "name" },
      { label: "Status", key: "status" },
      { label: "Priority", key: "priority" },
      { label: "Project", key: "projectName" },
      { label: "Assignees", key: "assignees" },
      { label: "Due Date", key: "dueDate", format: "date" },
      { label: "Source", key: "source" },
      { label: "Labels", key: "labels" },
      { label: "Description", key: "description" },
      { label: "Created", key: "createdAt", format: "date" },
    ],
  },
  submittal: {
    displayName: "Submittal",
    apiPath: "/api/submittals",
    listPath: "/execution/submittals",
    nameField: "name",
    statusField: "status",
    fields: [
      { label: "Submittal Number", key: "submittalNumber" },
      { label: "Name", key: "name" },
      { label: "Status", key: "status" },
      { label: "Priority", key: "priority" },
      { label: "Project", key: "projectName" },
      { label: "Type", key: "submittalType" },
      { label: "Revision", key: "revision" },
      { label: "Manager", key: "managerName" },
      { label: "Contractor", key: "contractorName" },
      { label: "Description", key: "description" },
      { label: "Created", key: "createdAt", format: "date" },
    ],
  },
  rfi: {
    displayName: "RFI",
    apiPath: "/api/rfis",
    listPath: "/execution/rfis",
    nameField: "subject",
    statusField: "status",
    fields: [
      { label: "RFI Number", key: "rfiNumber" },
      { label: "Subject", key: "subject" },
      { label: "Status", key: "status" },
      { label: "Priority", key: "priority" },
      { label: "Project", key: "projectName" },
      { label: "Question", key: "question" },
      { label: "Due Date", key: "dueDate", format: "date" },
      { label: "Created", key: "createdAt", format: "date" },
    ],
  },
  purchaseOrder: {
    displayName: "Purchase Order",
    apiPath: "/api/purchase-orders",
    listPath: "/execution/purchase-orders",
    nameField: "poNumber",
    statusField: "status",
    fields: [
      { label: "PO Number", key: "poNumber" },
      { label: "Status", key: "status" },
      { label: "Project", key: "projectName" },
      { label: "Total Amount", key: "totalAmount", format: "currency" },
      { label: "Order Date", key: "orderDate", format: "date" },
      { label: "Created", key: "createdAt", format: "date" },
    ],
  },
  changeOrder: {
    displayName: "Change Order",
    apiPath: "/api/change-orders",
    listPath: "/financial/change-orders",
    nameField: "title",
    statusField: "status",
    fields: [
      { label: "CO Number", key: "coNumber" },
      { label: "Title", key: "title" },
      { label: "Status", key: "status" },
      { label: "Change Type", key: "changeType" },
      { label: "Project", key: "projectName" },
      { label: "Amount", key: "amount", format: "currency" },
      { label: "Days Impact", key: "daysImpact" },
      { label: "Description", key: "description" },
      { label: "Created", key: "createdAt", format: "date" },
    ],
  },
  invoice: {
    displayName: "Invoice",
    apiPath: "/api/invoices",
    listPath: "/financial/invoices",
    nameField: "invoiceNumber",
    statusField: "status",
    fields: [
      { label: "Invoice Number", key: "invoiceNumber" },
      { label: "Type", key: "invoiceType" },
      { label: "Status", key: "status" },
      { label: "Project", key: "projectName" },
      { label: "Total Amount", key: "totalAmount", format: "currency" },
      { label: "Paid Amount", key: "paidAmount", format: "currency" },
      { label: "Invoice Date", key: "invoiceDate", format: "date" },
      { label: "Due Date", key: "dueDate", format: "date" },
      { label: "Created", key: "createdAt", format: "date" },
    ],
  },
  vendor: {
    displayName: "Vendor",
    apiPath: "/api/vendors",
    listPath: "/execution/vendors",
    nameField: "companyName",
    statusField: "status",
    fields: [
      { label: "Vendor Number", key: "vendorNumber" },
      { label: "Company Name", key: "companyName" },
      { label: "Type", key: "vendorType" },
      { label: "Status", key: "status" },
      { label: "Contact", key: "contactName" },
      { label: "Email", key: "email" },
      { label: "Phone", key: "phone" },
      { label: "Payment Terms", key: "paymentTerms" },
      { label: "Prequalification", key: "prequalificationStatus" },
      { label: "Performance Rating", key: "performanceRating" },
      { label: "Safety Rating", key: "safetyRating" },
      { label: "Bonding Capacity", key: "bondingCapacity", format: "currency" },
    ],
  },
  company: {
    displayName: "Company",
    apiPath: "/api/companies",
    listPath: "/capture/agencies",
    nameField: "name",
    statusField: "status",
    fields: [
      { label: "Name", key: "name" },
      { label: "Legal Name", key: "legalName" },
      { label: "DBA", key: "dba" },
      { label: "Type", key: "type" },
      { label: "Status", key: "status" },
      { label: "EIN", key: "ein" },
      { label: "CAGE Code", key: "cageCode" },
      { label: "UEI", key: "ueiNumber" },
      { label: "City", key: "city" },
      { label: "State", key: "state" },
      { label: "Phone", key: "phone" },
      { label: "Website", key: "website" },
      { label: "Primary Contact", key: "primaryContactName" },
      { label: "Contact Email", key: "primaryContactEmail" },
      { label: "Bonding Capacity", key: "bondingCapacity", format: "currency" },
    ],
  },
  ticket: {
    displayName: "Ticket",
    apiPath: "/api/tickets",
    listPath: "/execution/tickets",
    nameField: "title",
    statusField: "status",
    fields: [
      { label: "Title", key: "title" },
      { label: "Status", key: "status" },
      { label: "Priority", key: "priority" },
      { label: "Category", key: "category" },
      { label: "Assigned To", key: "assignedTo" },
      { label: "Description", key: "description" },
      { label: "Created", key: "createdAt", format: "date" },
    ],
  },
  opportunity: {
    displayName: "Opportunity",
    apiPath: "/api/opportunities",
    listPath: "/capture/opportunities",
    nameField: "title",
    statusField: "status",
    fields: [
      { label: "Title", key: "title" },
      { label: "Status", key: "status" },
      { label: "Agency", key: "agency" },
      { label: "Notice ID", key: "noticeId" },
      { label: "Type", key: "type" },
      { label: "Set-Aside", key: "setAside" },
      { label: "NAICS", key: "naicsCode" },
      { label: "Response Deadline", key: "responseDeadline", format: "date" },
      { label: "Posted Date", key: "postedDate", format: "date" },
      { label: "Place of Performance", key: "placeOfPerformance" },
      { label: "Description", key: "description" },
    ],
  },
  bidProject: {
    displayName: "Bid Project",
    apiPath: "/api/bid-projects",
    listPath: "/capture/pipeline",
    nameField: "name",
    statusField: "status",
    fields: [
      { label: "Name", key: "name" },
      { label: "Status", key: "status" },
      { label: "Stage", key: "stage" },
      { label: "Bid Number", key: "bidNumber" },
      { label: "Estimated Value", key: "estimatedValue", format: "currency" },
      { label: "Due Date", key: "dueDate", format: "date" },
      { label: "Description", key: "description" },
      { label: "Created", key: "createdAt", format: "date" },
    ],
  },
  competitor: {
    displayName: "Competitor",
    apiPath: "/api/competitors",
    listPath: "/capture/competitors",
    nameField: "name",
    statusField: "status",
    fields: [
      { label: "Name", key: "name" },
      { label: "Status", key: "status" },
      { label: "Website", key: "website" },
      { label: "Description", key: "description" },
      { label: "Created", key: "createdAt", format: "date" },
    ],
  },
};
