import { db } from "../db";
import { jacketFolders, jacketDocuments, bidProjects, opportunities, jacketBuildJobs, BID_JACKET_FOLDERS } from "@shared/schema";
import { eq, and } from "drizzle-orm";
import { objectStorageClient } from "../replit_integrations/object_storage/objectStorage";
import crypto from "crypto";

const DEFAULT_TENANT_ID = "blackhawk-default";

export interface OpportunityData {
  id: string;
  title: string;
  sourceSystemId: string | null;
  naicsCodes: string[] | null;
  setAside: string | null;
  dueAt: Date | null;
  description: string | null;
  synopsis: string | null;
  contractValue: number | null;
  status: string | null;
}

export interface GeneratedDocument {
  folderCode: string;
  title: string;
  fileName: string;
  documentType: string;
  generatedType: string;
  content: string;
  mimeType: string;
}

interface ArtifactResult {
  generatedType: string;
  folderCode: string;
  status: "created" | "skipped" | "failed";
  docId: string | null;
  message: string;
}

function formatDate(d: Date | null): string {
  if (!d) return "TBD";
  return new Date(d).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

function formatCurrency(amount: number | null): string {
  if (!amount) return "TBD";
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(amount);
}

function generateDocumentsFromOpportunity(opp: OpportunityData, bidProjectId: string): GeneratedDocument[] {
  const docs: GeneratedDocument[] = [];
  const today = formatDate(new Date());
  const naicsStr = (opp.naicsCodes || []).join(", ") || "N/A";
  const solNumber = opp.sourceSystemId || "N/A";

  docs.push({
    folderCode: "00",
    title: "Opportunity Summary",
    fileName: `Opportunity_Summary_${solNumber}.txt`,
    documentType: "summary",
    generatedType: "OpportunitySummary",
    mimeType: "text/plain",
    content: `OPPORTUNITY SUMMARY
${"=".repeat(60)}

Project: ${opp.title}
Solicitation Number: ${solNumber}
Agency/Buyer: BlackHawk Construction Internal Tracking
NAICS Code(s): ${naicsStr}
Set-Aside: ${opp.setAside || "Full & Open Competition"}
Contract Value: ${formatCurrency(opp.contractValue)}
Response Deadline: ${formatDate(opp.dueAt)}
Date Prepared: ${today}
Status: DRAFT - Auto-generated by HERBIE

${"─".repeat(60)}
PROJECT DESCRIPTION
${"─".repeat(60)}
${opp.description || opp.synopsis || "No description available. Review the original solicitation documents for full project scope."}

${"─".repeat(60)}
BID INTAKE CHECKLIST
${"─".repeat(60)}
[ ] Original solicitation document obtained
[ ] All amendments reviewed and acknowledged
[ ] Site visit scheduled/completed (if required)
[ ] Pre-bid conference attended (if applicable)
[ ] Bid bond requirements identified
[ ] Insurance requirements identified
[ ] Subcontractor requirements identified
[ ] DBE/SB goals identified
[ ] Technical evaluation criteria reviewed
[ ] Price evaluation criteria reviewed

${"─".repeat(60)}
NOTES
${"─".repeat(60)}
This summary was auto-generated by HERBIE from opportunity data.
Original solicitation documents should be obtained from the contracting office.
`,
  });

  docs.push({
    folderCode: "01",
    title: "Solicitation / Notice",
    fileName: `Solicitation_Notice_${solNumber}.txt`,
    documentType: "solicitation",
    generatedType: "SolicitationNotice",
    mimeType: "text/plain",
    content: `SOLICITATION / NOTICE
${"=".repeat(60)}

Project: ${opp.title}
Solicitation Number: ${solNumber}
Agency/Buyer: BlackHawk Construction
NAICS Code(s): ${naicsStr}
Set-Aside: ${opp.setAside || "Full & Open Competition"}
Contract Value: ${formatCurrency(opp.contractValue)}
Response Deadline: ${formatDate(opp.dueAt)}
Date Prepared: ${today}
Status: DRAFT

${"─".repeat(60)}
SOLICITATION DETAILS
${"─".repeat(60)}
${opp.description || opp.synopsis || "Full solicitation details pending. Download from SAM.gov or the contracting office."}

${"─".repeat(60)}
KEY REQUIREMENTS
${"─".repeat(60)}
- Review all amendments and modifications before submission
- Ensure compliance with all solicitation requirements
- Verify bonding requirements (if applicable)
- Check insurance certificate requirements
- Confirm past performance documentation is current

${"─".repeat(60)}
AMENDMENTS LOG
${"─".repeat(60)}
Amendment #   Date         Description
----------    ----------   ------------------------------------
(none yet)

${"─".repeat(60)}
STANDARD FEDERAL FORMS REQUIRED
${"─".repeat(60)}
[ ] SF-1442 - Solicitation, Offer and Award (Construction)
[ ] SF-30 - Amendment of Solicitation (all amendments)
[ ] SF-1413 - Statement and Acknowledgment
[ ] SF-25 - Performance Bond
[ ] SF-25A - Payment Bond

${"─".repeat(60)}
FAR REPRESENTATIONS & CERTIFICATIONS
${"─".repeat(60)}
[ ] FAR 52.204-8 - Annual Representations and Certifications
[ ] FAR 52.212-3 - Offeror Representations and Certifications
[ ] FAR 52.219-1 - Small Business Program Representations
[ ] FAR 52.222-22 - Previous Contracts and Compliance Reports
[ ] FAR 52.225-2 - Buy American Certificate

${opp.setAside ? `${"─".repeat(60)}
SET-ASIDE CERTIFICATIONS (${opp.setAside})
${"─".repeat(60)}
${opp.setAside === "SDVOSB" ? `[ ] VA Form 0877 - SDVOSB Certification
[ ] SBA VetCert Registration Current
[ ] Service-Disabled Veteran Status Documentation` :
  opp.setAside === "Small Business" ? `[ ] SBA Size Standard Compliance (NAICS ${naicsStr})
[ ] Small Business Self-Certification` :
  `[ ] Applicable certifications per solicitation requirements`}` : ""}
`,
  });

  docs.push({
    folderCode: "05",
    title: "Scope Extract + Risk Flags",
    fileName: `Scope_Extract_Risk_Flags_${solNumber}.txt`,
    documentType: "scope",
    generatedType: "ScopeExtractRiskFlags",
    mimeType: "text/plain",
    content: `SCOPE EXTRACT + RISK FLAGS
${"=".repeat(60)}

Project: ${opp.title}
Solicitation: ${solNumber}
Estimated Value: ${formatCurrency(opp.contractValue)}
NAICS: ${naicsStr}
Date: ${today}
Status: DRAFT

${"─".repeat(60)}
SCOPE OF WORK SUMMARY
${"─".repeat(60)}
${opp.description || opp.synopsis || "Scope details pending. Extract from solicitation documents when available."}

${"─".repeat(60)}
TRADE BREAKDOWN (PRELIMINARY)
${"─".repeat(60)}
Trade                     Self-Perform?   Sub Required?
-----------------------   -------------   -------------
General Conditions        [ ] Yes         [ ] No
Site Work / Earthwork     [ ] Yes         [ ] No
Concrete                  [ ] Yes         [ ] No
Structural Steel          [ ] Yes         [ ] No
Mechanical / HVAC         [ ] Yes         [ ] No
Electrical                [ ] Yes         [ ] No
Plumbing                  [ ] Yes         [ ] No
Fire Protection           [ ] Yes         [ ] No
Roofing                   [ ] Yes         [ ] No
Finishes                  [ ] Yes         [ ] No

${"─".repeat(60)}
RISK FLAGS
${"─".repeat(60)}
${opp.contractValue && Number(opp.contractValue) > 10000000 ? "[HIGH] Contract value exceeds $10M - enhanced bonding likely required" : ""}
${opp.setAside ? `[INFO] Set-aside requirement: ${opp.setAside} - verify eligibility` : ""}
${opp.dueAt && new Date(opp.dueAt).getTime() - Date.now() < 14 * 24 * 60 * 60 * 1000 ? "[HIGH] Response deadline is less than 14 days away - expedite bid preparation" : ""}
${!opp.description && !opp.synopsis ? "[MEDIUM] No scope description available - obtain original solicitation immediately" : ""}
[INFO] Verify site access requirements and security clearance needs
[INFO] Confirm prevailing wage / Davis-Bacon applicability
[INFO] Check liquidated damages clause terms

${"─".repeat(60)}
COST ESTIMATE WORKSHEET
${"─".repeat(60)}
1. LABOR
   Superintendent:           $_________ x _____ hrs = $_________
   Foreman:                  $_________ x _____ hrs = $_________
   Journeyman (Trade 1):     $_________ x _____ hrs = $_________
   Laborer:                  $_________ x _____ hrs = $_________
   TOTAL LABOR:                                       $_________

2. MATERIALS
   Item 1: _________________  Qty: ___  Unit: $___  = $_________
   Item 2: _________________  Qty: ___  Unit: $___  = $_________
   TOTAL MATERIALS:                                   $_________

3. EQUIPMENT
   Equipment 1: ____________  Days: ___  Rate: $___  = $_________
   TOTAL EQUIPMENT:                                   $_________

4. SUBCONTRACTORS
   Sub 1: _________________                          $_________
   Sub 2: _________________                          $_________
   TOTAL SUBCONTRACTORS:                              $_________

${"─".repeat(60)}
INDIRECT COSTS
${"─".repeat(60)}
   Overhead (____%):                                  $_________
   Profit (____%):                                    $_________
   Bond Premium (____%):                              $_________
   Insurance:                                         $_________
   Mobilization:                                      $_________
   TOTAL INDIRECT:                                    $_________

${"─".repeat(60)}
TOTAL BID AMOUNT:                                     $_________
`,
  });

  docs.push({
    folderCode: "08",
    title: "Compliance Checklist",
    fileName: `Compliance_Checklist_${solNumber}.txt`,
    documentType: "compliance",
    generatedType: "ComplianceChecklist",
    mimeType: "text/plain",
    content: `COMPLIANCE CHECKLIST
${"=".repeat(60)}

Project: ${opp.title}
Solicitation: ${solNumber}
Set-Aside: ${opp.setAside || "Full & Open"}
NAICS: ${naicsStr}
Date: ${today}
Status: DRAFT

${"─".repeat(60)}
REGISTRATION & ELIGIBILITY
${"─".repeat(60)}
[ ] SAM.gov registration active and current
[ ] DUNS / UEI number verified
[ ] CAGE code verified
[ ] NAICS code eligibility confirmed (${naicsStr})
${opp.setAside ? `[ ] ${opp.setAside} certification current and valid` : "[ ] Size standard compliance verified"}
[ ] State contractor license current
[ ] Federal contractor license (if required)

${"─".repeat(60)}
BONDING & INSURANCE
${"─".repeat(60)}
[ ] Bid bond obtained (typically 20% of bid)
[ ] Performance bond capacity confirmed (100% of contract)
[ ] Payment bond capacity confirmed (100% of contract)
[ ] General Liability ($1M/$2M minimum typical)
[ ] Workers Compensation (per state requirements)
[ ] Auto Liability ($1M minimum)
[ ] Umbrella/Excess ($5M minimum typical)
[ ] Builders Risk (if required)
[ ] Professional Liability (if design-build)

${"─".repeat(60)}
LABOR COMPLIANCE
${"─".repeat(60)}
[ ] Davis-Bacon prevailing wage rates obtained
[ ] Certified payroll process in place
[ ] EEO compliance documentation current
[ ] Drug-Free Workplace certification
[ ] E-Verify enrollment (if required)

${"─".repeat(60)}
SAFETY & QUALITY
${"─".repeat(60)}
[ ] EMR (Experience Modification Rate) documentation
[ ] OSHA 300 logs available (3 years)
[ ] Site-specific safety plan template ready
[ ] Quality control plan template ready
[ ] Environmental compliance plan (if required)

${"─".repeat(60)}
SUBMISSION COMPLIANCE
${"─".repeat(60)}
[ ] All required forms identified and obtained
[ ] Page limits reviewed and noted
[ ] Format requirements identified (electronic/hardcopy)
[ ] Submission method confirmed
[ ] Required copies count confirmed
[ ] Deadline: ${formatDate(opp.dueAt)}
`,
  });

  docs.push({
    folderCode: "12",
    title: "Submission Instructions",
    fileName: `Submission_Instructions_${solNumber}.txt`,
    documentType: "submission",
    generatedType: "SubmissionInstructions",
    mimeType: "text/plain",
    content: `SUBMISSION INSTRUCTIONS & FINAL CHECKLIST
${"=".repeat(60)}

Project: ${opp.title}
Solicitation: ${solNumber}
Submission Deadline: ${formatDate(opp.dueAt)}
Date: ${today}
Status: DRAFT

${"─".repeat(60)}
VOLUME 1 - TECHNICAL PROPOSAL
${"─".repeat(60)}
[ ] Cover letter / transmittal
[ ] Table of contents
[ ] Technical approach narrative
[ ] Management approach
[ ] Key personnel resumes
[ ] Organizational chart
[ ] Safety plan
[ ] Quality control plan
[ ] Project schedule
[ ] Subcontracting plan

${"─".repeat(60)}
VOLUME 2 - PAST PERFORMANCE
${"─".repeat(60)}
[ ] Past performance reference sheets (minimum 3)
[ ] CPARS/PPIRS documentation
[ ] Letters of recommendation
[ ] Project photos/descriptions

${"─".repeat(60)}
VOLUME 3 - PRICE PROPOSAL
${"─".repeat(60)}
[ ] Completed pricing schedule
[ ] Detailed cost breakdown
[ ] Labor rate justification
[ ] Subcontractor quotes
[ ] Equipment rates

${"─".repeat(60)}
ADMINISTRATIVE
${"─".repeat(60)}
[ ] All amendments acknowledged
[ ] Representations & certifications signed
[ ] Bid bond included
[ ] SAM.gov registration current
[ ] DUNS/UEI number verified
[ ] CAGE code verified
[ ] Required number of copies prepared
[ ] Electronic submission uploaded (if applicable)
[ ] Delivery method confirmed

${"─".repeat(60)}
FINAL REVIEW
${"─".repeat(60)}
[ ] All sections cross-referenced
[ ] Page limits verified
[ ] Signatures on all required documents
[ ] Proofread for errors
[ ] Compliant with all instructions
[ ] Deadline confirmed: ${formatDate(opp.dueAt)}

Reviewed by: _________________________________
Date: ________________________________________
`,
  });

  docs.push({
    folderCode: "11",
    title: "Bid Form Template",
    fileName: `Bid_Form_Template_${solNumber}.txt`,
    documentType: "bid_form",
    generatedType: "BidFormTemplate",
    mimeType: "text/plain",
    content: `BID FORM TEMPLATE
${"=".repeat(60)}

Project: ${opp.title}
Solicitation: ${solNumber}
Estimated Value: ${formatCurrency(opp.contractValue)}
Date: ${today}
Status: DRAFT

${"─".repeat(60)}
BASE BID
${"─".repeat(60)}
Item    Description                          Qty    Unit    Unit Price    Total
----    -----------------------------------  -----  ------  ----------    ----------
1       General Conditions                   1      LS      $________     $________
2       Site Preparation                     1      LS      $________     $________
3       Concrete Work                        1      LS      $________     $________
4       Structural Steel                     1      LS      $________     $________
5       Mechanical / HVAC                    1      LS      $________     $________
6       Electrical                           1      LS      $________     $________
7       Plumbing                             1      LS      $________     $________
8       Fire Protection                      1      LS      $________     $________
9       Finishes                             1      LS      $________     $________
10      Project Close-out                    1      LS      $________     $________

                                             BASE BID TOTAL:  $______________

${"─".repeat(60)}
ALTERNATES
${"─".repeat(60)}
Alt #   Description                                    Add        Deduct
------  -------------------------------------------    ---------  ---------
ALT-1   ________________________________________       $________  $________
ALT-2   ________________________________________       $________  $________
ALT-3   ________________________________________       $________  $________

${"─".repeat(60)}
ALLOWANCES
${"─".repeat(60)}
Item    Description                                    Amount
------  -------------------------------------------    ----------
A-1     Owner-directed allowance                       $________
A-2     Unforeseen conditions allowance                $________
A-3     ________________________________________       $________

${"─".repeat(60)}
EXCLUSIONS / INCLUSIONS
${"─".repeat(60)}
Exclusions:
1. _______________________________________________
2. _______________________________________________
3. _______________________________________________

Inclusions:
1. _______________________________________________
2. _______________________________________________
3. _______________________________________________

${"─".repeat(60)}
SCHEDULE
${"─".repeat(60)}
Proposed Start Date: ____________________
Proposed Completion Date: ____________________
Calendar Days: _______
Working Days: _______

${"─".repeat(60)}
CERTIFICATIONS
${"─".repeat(60)}
[ ] I certify that the prices quoted are firm for 90 days
[ ] I certify compliance with all solicitation requirements
[ ] I acknowledge receipt of all amendments

Authorized Signature: _______________________________
Printed Name: ______________________________________
Title: _____________________________________________
Date: ______________________________________________
Company: BlackHawk Construction
`,
  });

  return docs;
}

async function storeDocumentInObjectStorage(
  fileName: string,
  content: string,
  bidProjectId: string,
  mimeType: string
): Promise<{ storageKey: string; fileSize: number }> {
  const privateDir = process.env.PRIVATE_OBJECT_DIR || "";
  const objectPath = `${privateDir}/jackets/bid/${bidProjectId}/${fileName}`;
  
  const { bucketName, objectName } = parseObjectPath(objectPath);
  const bucket = objectStorageClient.bucket(bucketName);
  const file = bucket.file(objectName);
  
  const buffer = Buffer.from(content, "utf-8");
  await file.save(buffer, {
    contentType: mimeType,
    metadata: {
      bidProjectId,
      generatedBy: "herbie",
    },
  });

  const entityId = objectPath.replace(privateDir + "/", "");
  return {
    storageKey: `/objects/${entityId}`,
    fileSize: buffer.length,
  };
}

function parseObjectPath(path: string): { bucketName: string; objectName: string } {
  if (!path.startsWith("/")) path = `/${path}`;
  const parts = path.split("/");
  return {
    bucketName: parts[1],
    objectName: parts.slice(2).join("/"),
  };
}

export interface ScopeEnrichmentDeps {
  extract: (
    input: import("./herbie-scope-extractor.service").ScopeExtractionInput,
  ) => Promise<import("./herbie-scope-extractor.service").ScopeExtraction>;
  render: (
    input: import("./herbie-scope-extractor.service").ScopeExtractionInput,
    extraction: import("./herbie-scope-extractor.service").ScopeExtraction,
  ) => string;
}

async function defaultEnrichmentDeps(): Promise<ScopeEnrichmentDeps> {
  const mod = await import("./herbie-scope-extractor.service");
  return { extract: mod.extractSolicitationScope, render: mod.renderScopeExtractionMarkdown };
}

export async function enrichScopeExtractWithLLM(
  docs: GeneratedDocument[],
  opp: OpportunityData,
  jobId: string,
  depsOverride?: ScopeEnrichmentDeps,
): Promise<void> {
  const target = docs.find((d) => d.generatedType === "ScopeExtractRiskFlags");
  if (!target) return;

  try {
    const deps = depsOverride ?? (await defaultEnrichmentDeps());
    const solicitationNumber = opp.sourceSystemId || null;
    const extraction = await deps.extract({
      title: opp.title,
      solicitationNumber,
      agency: null,
      setAside: opp.setAside || null,
      contractValue: opp.contractValue ? Number(opp.contractValue) : null,
      naics: opp.naicsCodes || null,
      solicitationText: [opp.description, opp.synopsis].filter(Boolean).join("\n\n"),
    });
    const markdown = deps.render(
      {
        title: opp.title,
        solicitationNumber,
        solicitationText: "",
      },
      extraction,
    );
    target.content = markdown;
    target.fileName = target.fileName.replace(/\.txt$/, ".md");
    target.mimeType = "text/markdown";
    console.log(
      `[HERBIE-JACKET-BUILDER] Job ${jobId}: scope extraction (${extraction.source}, conf=${extraction.confidence.toFixed(2)})`,
    );
  } catch (err: any) {
    console.error(`[HERBIE-JACKET-BUILDER] Job ${jobId}: scope enrichment failed (keeping template): ${err?.message}`);
  }
}

export async function buildBidJacket(bidProjectId: string, mode: "build" | "repair" = "build"): Promise<{
  success: boolean;
  documentsCreated: number;
  documentsSkipped: number;
  documentsFailed: number;
  foldersPopulated: number;
  skipped: boolean;
  jobId: string;
  error?: string;
  artifacts: ArtifactResult[];
}> {
  const jobId = crypto.randomUUID();

  const [bidProject] = await db.select().from(bidProjects)
    .where(eq(bidProjects.id, bidProjectId));

  if (!bidProject) {
    await db.insert(jacketBuildJobs).values({
      id: jobId,
      tenantId: DEFAULT_TENANT_ID,
      bidProjectId,
      mode,
      status: "failed",
      docsCreated: 0,
      docsSkipped: 0,
      docsFailed: 0,
      resultJson: [],
      errorSummary: "Bid project not found",
      completedAt: new Date(),
    });
    return { success: false, documentsCreated: 0, documentsSkipped: 0, documentsFailed: 0, foldersPopulated: 0, skipped: false, jobId, error: "Bid project not found", artifacts: [] };
  }

  const folders = await db.select().from(jacketFolders)
    .where(and(
      eq(jacketFolders.tenantId, DEFAULT_TENANT_ID),
      eq(jacketFolders.jacketType, "bid"),
      eq(jacketFolders.jacketId, bidProjectId)
    ));

  if (folders.length === 0) {
    await db.insert(jacketBuildJobs).values({
      id: jobId,
      tenantId: DEFAULT_TENANT_ID,
      bidProjectId,
      mode,
      status: "failed",
      docsCreated: 0,
      docsSkipped: 0,
      docsFailed: 0,
      resultJson: [],
      errorSummary: "No jacket folders found. Create jacket first.",
      completedAt: new Date(),
    });
    return { success: false, documentsCreated: 0, documentsSkipped: 0, documentsFailed: 0, foldersPopulated: 0, skipped: false, jobId, error: "No jacket folders found. Create jacket first.", artifacts: [] };
  }

  await db.insert(jacketBuildJobs).values({
    id: jobId,
    tenantId: DEFAULT_TENANT_ID,
    bidProjectId,
    mode,
    status: "running",
    docsCreated: 0,
    docsSkipped: 0,
    docsFailed: 0,
    resultJson: [],
  });

  console.log(`[HERBIE-JACKET-BUILDER] Job ${jobId} started (mode=${mode}) for bid ${bidProjectId}`);

  let oppData: OpportunityData | null = null;
  if (bidProject.opportunityId) {
    const [opp] = await db.select().from(opportunities)
      .where(eq(opportunities.id, bidProject.opportunityId));
    if (opp) {
      oppData = {
        id: opp.id,
        title: opp.title,
        sourceSystemId: opp.sourceSystemId,
        naicsCodes: opp.naicsCodes,
        setAside: opp.setAside,
        dueAt: opp.dueAt,
        description: opp.description,
        synopsis: opp.synopsis,
        contractValue: opp.contractValue ? Number(opp.contractValue) : null,
        status: opp.status,
      };
    }
  }

  if (!oppData) {
    const oppTitle = bidProject.opportunityId
      ? `Bid Project ${bidProjectId.slice(0, 8)}`
      : `Bid Project ${bidProjectId.slice(0, 8)}`;
    oppData = {
      id: "unknown",
      title: oppTitle,
      sourceSystemId: bidProjectId.slice(0, 8),
      naicsCodes: [],
      setAside: null,
      dueAt: null,
      description: "No linked opportunity data available.",
      synopsis: null,
      contractValue: null,
      status: null,
    };
  }

  const folderMap = new Map<string, typeof folders[0]>();
  for (const f of folders) {
    let code: string;
    if (f.name.includes(" - ")) {
      code = f.name.split(" - ")[0].trim();
    } else if (f.name.includes("_")) {
      code = f.name.split("_")[0].trim();
    } else {
      code = f.name.trim();
    }
    folderMap.set(code, f);
  }

  const canonicalCodes = new Set(BID_JACKET_FOLDERS.map(f => f.code as string));

  function resolveFolder(folderCode: string): typeof folders[0] | undefined {
    if (!canonicalCodes.has(folderCode)) {
      console.warn(`[HERBIE-JACKET-BUILDER] folderCode "${folderCode}" not in canonical BID_JACKET_FOLDERS — skipping`);
      return undefined;
    }
    return folderMap.get(folderCode);
  }

  const generatedDocs = generateDocumentsFromOpportunity(oppData, bidProjectId);

  // Enrich the ScopeExtractRiskFlags doc with real LLM-driven extraction
  // when an Anthropic key is configured. The extractor degrades to a
  // deterministic fallback in stub mode, so this never blocks the build.
  await enrichScopeExtractWithLLM(generatedDocs, oppData, jobId);

  let documentsCreated = 0;
  let documentsSkipped = 0;
  let documentsFailed = 0;
  const populatedFolders = new Set<string>();
  const artifactResults: ArtifactResult[] = [];

  console.log(`[HERBIE-JACKET-BUILDER] Job ${jobId}: Processing ${generatedDocs.length} artifacts for bid ${bidProjectId}`);
  console.log(`[HERBIE-JACKET-BUILDER] Job ${jobId}: Available folder codes: ${Array.from(folderMap.keys()).join(", ")}`);

  for (const genDoc of generatedDocs) {
    const folder = resolveFolder(genDoc.folderCode);
    if (!folder) {
      console.warn(`[HERBIE-JACKET-BUILDER] Job ${jobId}: No folder for code "${genDoc.folderCode}" - skipping ${genDoc.generatedType}`);
      artifactResults.push({
        generatedType: genDoc.generatedType,
        folderCode: genDoc.folderCode,
        status: "failed",
        docId: null,
        message: `No folder found for code "${genDoc.folderCode}"`,
      });
      documentsFailed++;
      continue;
    }

    const existingDocs = await db.select().from(jacketDocuments)
      .where(and(
        eq(jacketDocuments.tenantId, DEFAULT_TENANT_ID),
        eq(jacketDocuments.folderId, folder.id),
        eq(jacketDocuments.generatedBy, "herbie"),
        eq(jacketDocuments.generatedType, genDoc.generatedType),
        eq(jacketDocuments.latestVersion, true)
      ));

    if (existingDocs.length > 0) {
      console.log(`[HERBIE-JACKET-BUILDER] Job ${jobId}: ${genDoc.generatedType} already exists in folder ${genDoc.folderCode} (docId=${existingDocs[0].id}) - skipping`);
      artifactResults.push({
        generatedType: genDoc.generatedType,
        folderCode: genDoc.folderCode,
        status: "skipped",
        docId: existingDocs[0].id,
        message: "Artifact already exists",
      });
      documentsSkipped++;
      continue;
    }

    try {
      const { storageKey, fileSize } = await storeDocumentInObjectStorage(
        genDoc.fileName,
        genDoc.content,
        bidProjectId,
        genDoc.mimeType
      );

      const docId = crypto.randomUUID();
      await db.insert(jacketDocuments).values({
        id: docId,
        tenantId: DEFAULT_TENANT_ID,
        folderId: folder.id,
        title: genDoc.title,
        fileName: genDoc.fileName,
        fileType: "txt",
        mimeType: genDoc.mimeType,
        fileSizeBytes: fileSize,
        storageKey,
        version: 1,
        latestVersion: true,
        documentType: genDoc.documentType,
        visibility: "internal",
        source: "herbie",
        sourceReference: `auto-build-${bidProjectId}`,
        generatedBy: "herbie",
        generatedType: genDoc.generatedType,
        status: "active",
      });

      console.log(`[HERBIE-JACKET-BUILDER] Job ${jobId}: Created ${genDoc.generatedType} (docId=${docId}) in folder ${genDoc.folderCode}`);

      artifactResults.push({
        generatedType: genDoc.generatedType,
        folderCode: genDoc.folderCode,
        status: "created",
        docId,
        message: `Stored at ${storageKey} (${fileSize} bytes)`,
      });

      documentsCreated++;
      populatedFolders.add(genDoc.folderCode);
    } catch (err: any) {
      console.error(`[HERBIE-JACKET-BUILDER] Job ${jobId}: Failed to create ${genDoc.generatedType}:`, err?.message || err);
      artifactResults.push({
        generatedType: genDoc.generatedType,
        folderCode: genDoc.folderCode,
        status: "failed",
        docId: null,
        message: err?.message || "Unknown error",
      });
      documentsFailed++;
    }
  }

  const totalRequired = generatedDocs.length;
  const jobStatus = documentsFailed > 0
    ? (documentsCreated > 0 ? "partial_success" : "failed")
    : "success";

  await db.update(jacketBuildJobs)
    .set({
      status: jobStatus,
      docsCreated: documentsCreated,
      docsSkipped: documentsSkipped,
      docsFailed: documentsFailed,
      resultJson: artifactResults,
      errorSummary: documentsFailed > 0
        ? artifactResults.filter(a => a.status === "failed").map(a => `${a.generatedType}: ${a.message}`).join("; ")
        : null,
      completedAt: new Date(),
    })
    .where(eq(jacketBuildJobs.id, jobId));

  console.log(`[HERBIE-JACKET-BUILDER] Job ${jobId} completed: status=${jobStatus}, created=${documentsCreated}, skipped=${documentsSkipped}, failed=${documentsFailed}`);

  return {
    success: jobStatus !== "failed",
    documentsCreated,
    documentsSkipped,
    documentsFailed,
    foldersPopulated: populatedFolders.size,
    skipped: documentsCreated === 0 && documentsFailed === 0,
    jobId,
    artifacts: artifactResults,
  };
}

export async function autoBuildAllEmptyJackets(): Promise<{
  processed: number;
  built: number;
  errors: string[];
}> {
  const allBidProjects = await db.select().from(bidProjects);
  let processed = 0;
  let built = 0;
  const errors: string[] = [];

  for (const bp of allBidProjects) {
    processed++;
    
    const folders = await db.select().from(jacketFolders)
      .where(and(
        eq(jacketFolders.tenantId, DEFAULT_TENANT_ID),
        eq(jacketFolders.jacketType, "bid"),
        eq(jacketFolders.jacketId, bp.id)
      ));

    if (folders.length === 0) continue;

    const folderIds = folders.map(f => f.id);
    let hasDocsInAnyFolder = false;
    for (const fId of folderIds) {
      const docs = await db.select().from(jacketDocuments)
        .where(and(
          eq(jacketDocuments.folderId, fId),
          eq(jacketDocuments.generatedBy, "herbie")
        ))
        .limit(1);
      if (docs.length > 0) {
        hasDocsInAnyFolder = true;
        break;
      }
    }

    if (hasDocsInAnyFolder) continue;

    try {
      const result = await buildBidJacket(bp.id);
      if (result.success && !result.skipped) built++;
      else if (result.error) errors.push(`${bp.id}: ${result.error}`);
    } catch (err: any) {
      errors.push(`${bp.id}: ${err.message}`);
    }
  }

  return { processed, built, errors };
}
